정방행렬은 고유분해(eigen-decomposition)로 고윳값과 고유벡터를 찾을 수 있었다. 정방행렬이 아닌 행렬은 고유분해가 불가능하다. 하지만 대신 고유분해와 비슷한 특이분해(singular decomposition)를 할 수 있다. (정방행렬이 아닌 경우 고유분해처럼 특이분해 가능)

### 특이값과 특이벡터
𝑁×𝑀  크기의 행렬  𝐴 를 다음과 같은 3개의 행렬의 곱으로 나타내는 것을 특이분해(singular-decomposition) 또는 특이값 분해(singular value decomposition)라고 한다.

\begin{align}
A = U\Sigma V^T 
\end{align}

여기에서  𝑈,Σ,𝑉 는 다음 조건을 만족해야 한다.
+ 대각성분이 양수인 대각행렬이어야 한다. 큰 수부터 작은 수 순서로 배열한다.
\begin{align}
\Sigma \in \mathbf{R}^{N \times M}
\end{align}
+ 𝑈 는  𝑁 차원 정방행렬로 모든 열벡터가 단위벡터이고 서로 직교해야 한다(orthonormal).
\begin{align}
U \in \mathbf{R}^{N \times N}
\end{align}
+ 𝑉 는 𝑀차원 정방행렬로 모든 열벡터가 단위벡터이고 서로 직교해야 한다(orthonormal).
\begin{align}
V \in \mathbf{R}^{M \times M}
\end{align}

위 조건을 만족하는 행렬  𝑆 의 대각성분들을 특이값(singular value), 행렬 𝑈 의 열벡터들을 왼쪽 특이벡터(left singular vector), 행렬  𝑣 의 행벡터들을 오른쪽 특이벡터(right singular vector)라고 부른다.

[정리] 특이분해는 모든 행렬에 대해 가능하다. 즉 어떤 행렬이 주어지더라도 위와 같이 특이분해할 수 있다.

### 특이값 분해 행렬의 크기

특이값의 개수는 행렬의 열과 행의 개수 중 작은 값과 같다. 특이분해된 형태를 구체적으로 쓰면 다음과 같다.

만약  𝑁>𝑀 이면  Σ 행렬이  𝑀개의 특이값(대각성분)을 가지고 다음과 같이 아랫 부분이 영행렬이 된다.

\begin{align}
A = 
\begin{bmatrix}
\boxed{\begin{matrix} \\ \\ \\ \\ \\ \, u_1 \, \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\ \, u_2 \, \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\ \, u_3 \, \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\cdots \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\  u_M  \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!&
\cdots \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\ u_N \\ \\ \\ \\ \\ \\ \end{matrix}} 
\end{bmatrix}
\begin{bmatrix}
\boxed{\sigma_1 \phantom{\dfrac{}{}} \!\!} & 0 & 0 & \cdots & 0 \\
0 & \boxed{\sigma_2 \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 \\
0 & 0 & \boxed{\sigma_3 \phantom{\dfrac{}{}} \!\!} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots \\
0 & 0 & 0 & \cdots & \boxed{\sigma_M \phantom{\dfrac{}{}} \!\!} \\
0 & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots &  & \vdots \\
0 & 0 & 0 & \cdots & 0 \\
\end{bmatrix}
\begin{bmatrix}
\boxed{\begin{matrix} & & & v_1^T & & & \end{matrix}} \\ 
\boxed{\begin{matrix} & & & v_2^T & & & \end{matrix}} \\ 
\vdots \\ 
\boxed{\begin{matrix} & & & v_M^T & & & \end{matrix}} \\ 
\end{bmatrix}
\end{align}


반대로  𝑁<𝑀 이면  Σ  행렬이  𝑁 개의 특잇값(대각성분)을 가지고 다음처럼 오른쪽 부분이 영행렬이 된다.

\begin{align}
A = 
\begin{bmatrix}
\boxed{\begin{matrix} \\ \\ \\ \, u_1 \, \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \, u_2 \, \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\cdots \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ u_N \\ \\ \\ \\ \end{matrix}} 
\end{bmatrix}
\begin{bmatrix}
\boxed{\sigma_1 \phantom{\dfrac{}{}} \!\!} & 0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
0 & \boxed{\sigma_2 \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 & 0 & \cdots & 0 \\
0 & 0 & \boxed{\sigma_3 \phantom{\dfrac{}{}} \!\!} & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots & & \vdots \\
0 & 0 & 0 & \cdots & \boxed{\sigma_N \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 \\
\end{bmatrix}
\begin{bmatrix}
\boxed{\begin{matrix} \quad & \quad & \quad & v_1^T & \quad & \quad & \quad \end{matrix}} \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_2^T & \quad & \quad & \quad \end{matrix}} \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_3^T & \quad & \quad & \quad \end{matrix}} \\ 
\vdots \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_N^T & \quad & \quad & \quad \end{matrix}} \\ 
\vdots \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_M^T & \quad & \quad & \quad \end{matrix}} \\ 
\end{bmatrix}
\end{align}

행렬의 크기만 표시하면 다음과 같다.
\begin{align}
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\; &   & \; \\
\; &   & \; \\
\; & A & \; \\
\; &   & \; \\
\; &   & \; \\
\end{matrix}
}}^{\large M}
=
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\; & & & & \quad \\
\; & & & & \quad \\
\; & & \; U & & \quad \\
\; & & & & \quad \\
\; & & & & \quad \\
\end{matrix}
}}^{\large N}
\;
\overbrace{
\boxed{
\begin{matrix}
& & \\
& & \\
& \Sigma & \\
& & \\
& & \\
\end{matrix}
}}^{\large M}
\;
\overbrace{
\boxed{
\begin{matrix}
\; &   & \; \\
\; & V & \; \\
\; &   & \; \\
\end{matrix}
}}^{\large M}
\!\!\left.\phantom{\begin{matrix} \\ \\ \\ \end{matrix}}\right\}M
\end{align}

또는
\begin{align}
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\quad & &   & & \quad \\
\quad & & A & & \quad \\
\quad & &   & & \quad \\
\end{matrix}
}}^{\large M}
=
N\;\left\{\phantom{\begin{matrix} \\ \\ \\  \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\begin{matrix}
\, & & \; \\
\, & U \; \\
\, & & \; \\
\end{matrix}
\end{matrix}
}}^{\large N}
\;
\overbrace{
\boxed{
\begin{matrix}
\quad & &   & & \quad \\
\quad & & \Sigma & & \quad \\
\quad & &   & & \quad \\
\end{matrix}
}}^{\large M}
\;
\overbrace{
\boxed{
\begin{matrix}
\; & & & & \quad \\
\; & & & & \quad \\
\; & & \; V & & \quad \\
\; & & & & \quad \\
\; & & & & \quad \\
\end{matrix}
}}^{\large M}
\!\!\left.\phantom{\begin{matrix} \\ \\ \\\\ \\ \end{matrix}}\right\}M
\end{align}

#### 예제 1.
행렬  𝐴
\begin{align}
A = 
\begin{bmatrix}
3 & -1 \\
1 & 3 \\
1 & 1
\end{bmatrix}
\end{align}

는 다음처럼 특이분해할 수 있다.
\begin{align}
A = 
\begin{bmatrix}
 -\frac{1}{\sqrt{6}} &  \frac{2}{\sqrt{5}} & -\frac{1}{\sqrt{6}} \\ 
 -\frac{2}{\sqrt{6}} & -\frac{1}{\sqrt{5}} &  -\frac{2}{\sqrt{30}} \\ 
 -\frac{1}{\sqrt{6}} & 0 &  \frac{5}{\sqrt{30}}
\end{bmatrix}
\begin{bmatrix}
\sqrt{12} & 0        \\
       0  & \sqrt{10} \\
       0 & 0 
\end{bmatrix}
\begin{bmatrix}
-\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
 \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} 
\end{bmatrix}
\end{align}

### 특이값 분해의 축소형

특이값 대각행렬에서 0인 부분은 사실상 아무런 의미가 없기 때문에 대각행렬의 0 원소 부분과 이에 대응하는 왼쪽(혹은 오른쪽) 특이벡터들을 없애고 다음처럼 축소된 형태로 해도 마찬가지로 원래 행렬이 나온다.

𝑁 이  𝑀 보다 큰 경우에는 왼쪽 특이벡터 중에서  $u_{M+1}, \cdots, u_N$을 없앤다.

\begin{align}
A = 
\begin{bmatrix}
\boxed{\begin{matrix} \\ \\ \\ \\ \\ \, u_1 \, \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\ \, u_2 \, \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\cdots \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \\ \\  u_M  \\ \\ \\ \\ \\ \\ \end{matrix}} \!\!\!\!&
\end{bmatrix}
\begin{bmatrix}
\boxed{\sigma_1 \phantom{\dfrac{}{}} \!\!} & 0 & 0 & \cdots & 0 \\
0 & \boxed{\sigma_2 \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 \\
0 & 0 & \boxed{\sigma_3 \phantom{\dfrac{}{}} \!\!} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots \\
0 & 0 & 0 & \cdots & \boxed{\sigma_M \phantom{\dfrac{}{}} \!\!} \\
0 & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots &  & \vdots \\
0 & 0 & 0 & \cdots & 0 \\
\end{bmatrix}
\begin{bmatrix}
\boxed{\begin{matrix} & & & v_1^T & & & \end{matrix}} \\ 
\boxed{\begin{matrix} & & & v_2^T & & & \end{matrix}} \\ 
\vdots \\ 
\boxed{\begin{matrix} & & & v_M^T & & & \end{matrix}} \\ 
\end{bmatrix}
\end{align}

𝑁 이 𝑀보다 작은 경우에는 오른쪽 특이벡터 중에서 𝑣𝑁+1,⋯,𝑣𝑀을 없앤다.
\begin{align}
A = 
\begin{bmatrix}
\boxed{\begin{matrix} \\ \\ \\ \, u_1 \, \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ \, u_2 \, \\ \\ \\ \\ \end{matrix}} \!\!\!\!& 
\cdots \!\!\!\!& 
\boxed{\begin{matrix} \\ \\ \\ u_N \\ \\ \\ \\ \end{matrix}} 
\end{bmatrix}
\begin{bmatrix}
\boxed{\sigma_1 \phantom{\dfrac{}{}} \!\!} & 0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
0 & \boxed{\sigma_2 \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 & 0 & \cdots & 0 \\
0 & 0 & \boxed{\sigma_3 \phantom{\dfrac{}{}} \!\!} & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots & & \vdots \\
0 & 0 & 0 & \cdots & \boxed{\sigma_N \phantom{\dfrac{}{}} \!\!} & 0 & \cdots & 0 \\
\end{bmatrix}
\begin{bmatrix}
\boxed{\begin{matrix} \quad & \quad & \quad & v_1^T & \quad & \quad & \quad \end{matrix}} \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_2^T & \quad & \quad & \quad \end{matrix}} \\ 
\vdots \\ 
\boxed{\begin{matrix} \quad & \quad & \quad & v_N^T & \quad & \quad & \quad \end{matrix}} \\ 
\end{bmatrix}
\end{align}

축소형의 경우에도 행렬의 크기만 표시하면 다음과 같다.
\begin{align}
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\; &   & \; \\
\; &   & \; \\
\; & A & \; \\
\; &   & \; \\
\; &   & \; \\
\end{matrix}
}}^{\large M}
=
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
& & \\
& & \\
& U & \\
& & \\
& & \\
\end{matrix}
}}^{\large M}
\;
\overbrace{
\boxed{
\begin{matrix}
\; &   & \; \\
\; & \Sigma & \; \\
\; &   & \; \\
\end{matrix}
}}^{\large M}
\;
\overbrace{
\boxed{
\begin{matrix}
\; &   & \; \\
\; & V & \; \\
\; &   & \; \\
\end{matrix}
}}^{\large M}
\!\!\left.\phantom{\begin{matrix} \\ \\ \\ \end{matrix}}\right\}M
\end{align}

또는
\begin{align}
N\;\left\{\phantom{\begin{matrix} \\ \\ \\ \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\quad & &   & & \quad \\
\quad & & A & & \quad \\
\quad & &   & & \quad \\
\end{matrix}
}}^{\large M}
=
N\;\left\{\phantom{\begin{matrix} \\ \\ \\  \end{matrix}}\right.\!\!
\overbrace{
\boxed{
\begin{matrix}
\begin{matrix}
\, & & \; \\
\, & U \; \\
\, & & \; \\
\end{matrix}
\end{matrix}
}}^{\large N}
\;
\overbrace{
\boxed{
\begin{matrix}
\, & & \; \\
\, & \Sigma \; \\
\, & & \; \\
\end{matrix}
}}^{\large N}
\;
\overbrace{
\boxed{
\begin{matrix}
\quad & &   & & \quad \\
\quad & & V & & \quad \\
\quad & &   & & \quad \\
\end{matrix}
}}^{\large M}
\!\!\left.\phantom{\begin{matrix} \\ \\ \\ \end{matrix}}\right\}N
\end{align}

#### 예제 2.
행렬  𝐴

\begin{align}
A = 
\begin{bmatrix}
3 & -1 \\
1 & 3 \\
1 & 1
\end{bmatrix}
\end{align}

의 특이분해 축소형은 다음과 같다.
\begin{align}
A = 
\begin{bmatrix}
 -\frac{1}{\sqrt{6}} &  \frac{2}{\sqrt{5}} \\ 
 -\frac{2}{\sqrt{6}} & -\frac{1}{\sqrt{5}} \\ 
 -\frac{1}{\sqrt{6}} & 0 
\end{bmatrix}
\begin{bmatrix}
\sqrt{12} & 0        \\
       0  & \sqrt{10} \\
\end{bmatrix}
\begin{bmatrix}
-\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
 \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} 
\end{bmatrix}
\end{align}

### 파이썬을 사용한 특이분해
numpy.linalg 서브패키지와 scipy.linalg 서브패키지에서는 특이분해를 할 수 있는 svd 명령을 제공한다. 오른쪽 특이행렬은 전치행렬로 출력된다는 점에 주의하라.

In [2]:
import numpy as np
from numpy.linalg import svd

A = np.array([[3, -1], [1, 3], [1, 1]])
U, S, VT = svd(A)

In [3]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [4]:
S

array([3.46410162, 3.16227766])

In [5]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
V = VT.T

In [7]:
V

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

In [8]:
np.diag(S, 1)[:, 1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [10]:
np.diag(S)

array([[3.46410162, 0.        ],
       [0.        , 3.16227766]])

In [11]:
U @ np.diag(S, 1)[:, 1:] @ VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

축소형을 구하려면 인수 full_matrices=False로 지정한다.

In [12]:
U2, S2, VT2 = svd(A, full_matrices=False)

In [13]:
U2

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -1.94289029e-16]])

In [14]:
S2

array([3.46410162, 3.16227766])

In [16]:
VT2

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [17]:
U2 @ np.diag(S2) @ VT2

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

### Practice 1
NumPy를 사용하여 다음 행렬을 특이값 분해를 한다(축소형이 아닌 방법과 축소형 방법을 각각 사용한다). 또한 다시 곱해서 원래의 행렬이 나오는 것을 보여라.
\begin{align}
B =
\begin{bmatrix}
3 & 2 & 2 \\
2 & 3 & -2
\end{bmatrix}
\end{align}
\begin{align}
C =
\begin{bmatrix}
2 & 4 \\
1 & 3 \\
0 & 0 \\
0 & 0 \\
\end{bmatrix}
\end{align}

In [18]:
B = np.array([[3, 2, 2], [2, 3, -2]])
C = np.array([[2, 4], [1, 3], [0, 0], [0, 0]])

In [19]:
UB, SB, VTB = svd(B)

In [31]:
np.diag(SB, 1)

array([[0., 5., 0.],
       [0., 0., 3.],
       [0., 0., 0.]])

In [24]:
UB

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [25]:
VTB

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [51]:
UB @ np.hstack([np.diag(SB), np.zeros((2, 1))]) @ VTB

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [52]:
UC, SC, VTC = svd(C)

In [53]:
UC

array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
       [-0.57604844,  0.81741556,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [54]:
SC

array([5.4649857 , 0.36596619])

In [55]:
VTC

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [59]:
UC @ np.diag(SC, 2)[:, 2:] @ VTC

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])

In [60]:
UB2, SB2, VTB2 = svd(B, full_matrices=False)
UB2

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [61]:
SB2

array([5., 3.])

In [62]:
VTB2

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]])

In [64]:
UB2 @ np.diag(SB2) @ VTB2

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [65]:
UC2, SC2, VTC2 = svd(C, full_matrices=False)

In [66]:
UC2 @ np.diag(SC2) @ VTC2

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])